---
- name: happy pass
  hosts: web_server
  remote_user: ubuntu
  tasks:
  - name: "execute a ls cmd"
    shell: "ls -lrt"
    register: shell_result
- name: Install Java
  hosts: web_server
  remote_user: ubuntu
  become: yes
  tasks:
    - name: update apt cache
      apt:
        update_cache: yes
    - name: installing jdk8
      apt:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
          - openjdk-8-jdk
# - name: Install Maven
#   hosts: web_server
#   remote_user: ubuntu
#   become: yes
#   tasks:
#     - name: installing maven
#       yum: name=maven state=latest
# - name: Copy Snapshot
#   hosts: web_server
#   remote_user: ubuntu
#   become: yes
#   tasks:
#     - name: copying jar file
#       copy:
#         src: /var/jenkins_home/workspace/petclinic-ci/target/spring-petclinic-2.7.3.jar 
#         dest: /home/ubuntu/jenkins/snapshot.jar
# - name: Run petclinic
#   hosts: web_server
#   remote_user: ubuntu
#   become: yes
#   become_user: root
#   tasks:
#     - name: running petclinic
#       systemd:
#         name: petclinic
#         state: started
